---
- hosts: all
  become: yes
  tasks:
    - name: Create the wheel groups
      group:
        name: wheel
        state: present
    - name: Create User
      user:
        name: testuser
        groups: wheel
        append: true